// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Used by the Prisma CLI (migrate, studio, db pull/push) — point this at Neon's
  // *direct* (unpooled) connection string since migrations need a session-level
  // connection. The app's runtime PrismaClient uses the pooled DATABASE_URL via
  // the Neon driver adapter instead (see src/lib/prisma.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
